# setup vars
environ:                "stage" # dev || stage || prod
debugging:              true

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# deployment vars
app_branch:             "main"

# ruby vars
chruby_ruby_version:    "ruby-2.6.6"

# rails vars
rails_env:              "production"

# apache vars:
hostname:               "{{ app_name }}"
domainname:             "library.jhu.edu"

# passenger vars
 # TODO: adopt and move up
update_packages:        false

# database config vars
# catalyst_db
catalyst_db_name:       "catalyst_dev"
catalyst_db_host:       "mysql.dev.mse.jhu.edu"
catalyst_db_user:       "{{ vault_catalyst_db_user }}"
catalyst_db_pass:       "{{ vault_catalyst_db_pass }}"
catalyst_db_port:       3306
# horizon_db
horizon_db_name:        "horizonstage"
horizon_db_host:        "horizontest.mse.jhu.edu"
horizon_db_user:        "{{ vault_horizon_db_user }}"
horizon_db_pass:        "{{ vault_horizon_db_pass }}"
horizon_db_port:        2025

# hip server vars
hip_host:               "hip-stage.library.jhu.edu"
horizon_ws_url:         "http://localhost:8080/ws" # default
borrower_ws_username:   "{{ vault_borrower_ws_username }}"
borrower_ws_password:   "{{ vault_borrower_ws_password }}"
force_default_jhed:     "{{ vault_force_default_jhed }}"

# borrow_direct vars
borrow_direct_host:     "bd-test.relaisd2d.com"

# Flipper auth vars
flipper_username:       "{{ vault_flipper_username }}"
flipper_password:       "{{ vault_flipper_password }}"

# Rollbar access token vars
rollbar_access_token:   "{{ vault_rollbar_access_token }}"
rollbar_env:            "stage"

# Sentry.io
sentry_dsn:             "{{ vault_sentry_dsn }}"
sentry_env:             "stage"

# Google API for retrieving book covers
google_books_api_key: "{{ vault_google_books_api_key }}"

# catalyst/findit vars
# catalyst_base_url is a callback used by findit. It has to be a server that findit can access
catalyst_base_url:      "https://catalyst-stage.library.jhu.edu"
findit_base_url:        "https://findit-test.library.jhu.edu" # we do not have a findit-stage server

# solr vars
solr_url:               "{{ vault_solr_url }}"

# firewalld vars:
# NOTE: this is important to do at least once, as we are using some of
# firewall-cmd's recently added capabilities:
firewalld_update_packages:  true
firewalld_ipsets:
  - name: jetty_whitelist
    ips:
      - "{{ findit_ip_test }}"
  - name: catalyst_whitelist
    ips: "{{ refworks_ips + [findit_ip_test] + [hopkins_ip_range] }}"
firewalld_richrules:
  - rule: "{{ jetty_accept_rule }}"
    state: enabled
  - rule: "{{ jetty_reject_rule }}"
    state: enabled
  - rule: "{{ catalyst_http_accept_rule }}"
    state: enabled
  - rule: "{{ catalyst_http_reject_rule }}"
    state: enabled
  - rule: "{{ catalyst_https_accept_rule }}"
    state: enabled
  - rule: "{{ catalyst_https_reject_rule }}"
    state: enabled

sfx_base_url: "https://sfx-stage.library.jhu.edu/sfxlcl41"