# setup vars
mode:                         "deploy" # dev || deploy

# ruby vars
# chruby_ruby_version:          "jruby-9.1.12.0"
service_ruby_version:         "jruby-1.7.4"
service_ruby_path:            "/opt/rubies/{{ service_ruby_version }}"
chruby_ruby_version:          "{{ service_ruby_version }}"

app_name:                     "pull_reserves"
app_user:                     "catalyst"
app_group:                    "{{ app_user }}"
download_dir:                 "/home/{{ login_user }}/{{ app_name }}"

# rails vars
rails_env:                    "production"
